from __future__ import annotations
"""
test_ml_scorer.py

Unit tests for the ML scorer layer:
  - threshold_policy.py
  - shap_explainer.py
  - xgboost_scorer.py
  - 02_model_training.py (integration smoke)

All tests run with zero external dependencies:
  - No Redis (in-memory store)
  - No Postgres
  - No API keys
  - Model loaded from models/xgboost_v1.json (generated by training script)
"""
import pytest
import xgboost as xgb
import os
import numpy as np
from datetime import datetime, timezone

from ingestion.schemas.transaction_event import TransactionEvent, RiskClass
from features.redis_client import FeatureStoreClient
from features.feature_pipeline import build_feature_vector
from features.models import FeatureVector

from prediction.ml_scorer.threshold_policy import classify_risk, get_thresholds
from prediction.ml_scorer.shap_explainer import (
    SHAPExplainer, SHAPExplanation, FeatureContribution,
)
from prediction.ml_scorer.xgboost_scorer import (
    score_transaction, ScorerOutput, FEATURE_NAMES,
    _BOOSTER, _MODEL_VERSION, _heuristic_score, _heuristic_shap,
)


# ── Shared helpers ─────────────────────────────────────────────────────────

def make_event(**overrides) -> TransactionEvent:
    defaults = dict(
        transaction_id="TXN-ML-001",
        customer_id="CUST-ML-42",
        amount=5000.0,
        currency="USD",
        channel="WIRE",
        origin_account="ACC-US-001",
        destination_account="ACC-US-002",
        jurisdiction_origin="US",
        jurisdiction_destination="US",
        product_type="WIRE_TRANSFER",
        timestamp=datetime(2026, 6, 13, 10, 0, 0, tzinfo=timezone.utc),
    )
    defaults.update(overrides)
    return TransactionEvent(**defaults)


def make_store(**kwargs) -> FeatureStoreClient:
    store = FeatureStoreClient()
    store.seed_customer(
        "CUST-ML-42",
        avg_amount=kwargs.get("avg_amount", 5000.0),
        risk_rating=kwargs.get("risk_rating", 2),
        prior_alerts=kwargs.get("prior_alerts", 0),
        account_age_days=kwargs.get("account_age_days", 365),
    )
    return store


def make_fv(**event_overrides) -> FeatureVector:
    event = make_event(**event_overrides)
    store = make_store()
    return build_feature_vector(event, store)


# ══════════════════════════════════════════════════════════════════════════
# 1. threshold_policy.py
# ══════════════════════════════════════════════════════════════════════════

class TestThresholdPolicy:

    def test_high_score_returns_high_class(self):
        assert classify_risk(0.90) == RiskClass.HIGH

    def test_medium_score_returns_medium_class(self):
        assert classify_risk(0.55) == RiskClass.MEDIUM

    def test_low_score_returns_low_class(self):
        assert classify_risk(0.20) == RiskClass.LOW

    def test_exact_high_boundary(self):
        # Score exactly at high threshold should return HIGH
        thresholds = get_thresholds("DEFAULT", "DEFAULT")
        assert classify_risk(thresholds["high"]) == RiskClass.HIGH

    def test_just_below_high_boundary(self):
        thresholds = get_thresholds("DEFAULT", "DEFAULT")
        score = thresholds["high"] - 0.001
        assert classify_risk(score) == RiskClass.MEDIUM

    def test_exact_medium_boundary(self):
        thresholds = get_thresholds("DEFAULT", "DEFAULT")
        assert classify_risk(thresholds["medium"]) == RiskClass.MEDIUM

    def test_just_below_medium_boundary(self):
        thresholds = get_thresholds("DEFAULT", "DEFAULT")
        score = thresholds["medium"] - 0.001
        assert classify_risk(score) == RiskClass.LOW

    def test_wire_transfer_to_ae_has_lower_threshold(self):
        # AE-specific threshold should be lower than DEFAULT
        ae_thresholds      = get_thresholds("WIRE_TRANSFER", "AE")
        default_thresholds = get_thresholds("WIRE_TRANSFER", "DEFAULT")
        assert ae_thresholds["high"] < default_thresholds["high"]

    def test_unknown_product_falls_back_to_default(self):
        # Unknown product should not crash — uses DEFAULT
        result = classify_risk(0.80, product_type="CRYPTO_TRANSFER")
        assert result in (RiskClass.HIGH, RiskClass.MEDIUM, RiskClass.LOW)

    def test_unknown_jurisdiction_falls_back_to_product_default(self):
        result = classify_risk(0.80, jurisdiction_destination="ZZ")
        assert result in (RiskClass.HIGH, RiskClass.MEDIUM, RiskClass.LOW)

    def test_ach_has_higher_threshold_than_swift(self):
        # ACH is lower risk channel — higher thresholds before flagging
        ach_thresh  = get_thresholds("ACH",   "DEFAULT")
        swift_thresh = get_thresholds("SWIFT", "DEFAULT")
        assert ach_thresh["high"] > swift_thresh["high"]

    def test_score_zero_is_low(self):
        assert classify_risk(0.0) == RiskClass.LOW

    def test_score_one_is_high(self):
        assert classify_risk(1.0) == RiskClass.HIGH

    def test_get_thresholds_returns_high_and_medium_keys(self):
        t = get_thresholds()
        assert "high" in t
        assert "medium" in t

    def test_medium_threshold_always_below_high(self):
        for product in ["DEFAULT", "WIRE_TRANSFER", "ACH", "SWIFT"]:
            t = get_thresholds(product)
            assert t["medium"] < t["high"], f"medium >= high for product={product}"


# ══════════════════════════════════════════════════════════════════════════
# 2. shap_explainer.py
# ══════════════════════════════════════════════════════════════════════════

class TestSHAPExplainer:

    @pytest.fixture(scope="class")
    def explainer(self):
        """Create a real SHAPExplainer using the trained model."""
        if _BOOSTER is None:
            pytest.skip("XGBoost model not found — run notebooks/02_model_training.py first")
        return SHAPExplainer(_BOOSTER, FEATURE_NAMES, _MODEL_VERSION)

    @pytest.fixture(scope="class")
    def sample_input(self):
        """A high-risk feature vector as numpy array."""
        fv = make_fv(
            amount=95000.0,
            jurisdiction_destination="AE",
            timestamp=datetime(2026, 6, 13, 2, 0, 0, tzinfo=timezone.utc),
        )
        return np.array([fv.to_model_input()])

    def test_returns_shap_explanation_object(self, explainer, sample_input):
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score)
        assert isinstance(result, SHAPExplanation)

    def test_top_features_count_default_5(self, explainer, sample_input):
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score)
        assert len(result.top_features) == 5

    def test_top_features_count_custom(self, explainer, sample_input):
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score, top_n=3)
        assert len(result.top_features) == 3

    def test_features_sorted_by_abs_contribution(self, explainer, sample_input):
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score)
        abs_contribs = [f.abs_contribution for f in result.top_features]
        assert abs_contribs == sorted(abs_contribs, reverse=True)

    def test_feature_names_are_valid(self, explainer, sample_input):
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score)
        for f in result.top_features:
            assert f.feature in FEATURE_NAMES

    def test_predicted_score_stored_correctly(self, explainer, sample_input):
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score)
        assert abs(result.predicted_score - round(predicted_score, 4)) < 1e-6

    def test_base_value_is_float(self, explainer, sample_input):
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score)
        assert isinstance(result.base_value, float)

    def test_model_version_matches(self, explainer, sample_input):
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score)
        assert result.model_version == _MODEL_VERSION

    def test_abs_contribution_equals_abs_of_contribution(self, explainer, sample_input):
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score)
        for f in result.top_features:
            assert abs(round(f.contribution, 4)) == f.abs_contribution

    def test_high_risk_features_have_positive_contributions(self, explainer, sample_input):
        """For a genuinely high-risk transaction, top features should push score UP."""
        predicted_score = float(_BOOSTER.predict(xgb.DMatrix(sample_input, feature_names=FEATURE_NAMES))[0])
        result = explainer.explain(sample_input, predicted_score)
        # At least the top feature should be positive for a high-risk case
        assert result.top_features[0].contribution > 0


# ══════════════════════════════════════════════════════════════════════════
# 3. xgboost_scorer.py — heuristic fallback
# ══════════════════════════════════════════════════════════════════════════

class TestHeuristicScorer:
    """Tests for the rule-based fallback scorer (no model needed)."""

    def _make_fv(self, **kwargs) -> FeatureVector:
        defaults = dict(
            transaction_id="TXN-HEUR-001",
            customer_id="CUST-HEUR-42",
            count_24h=0, count_7d=0, sum_24h=0.0, sum_7d=0.0,
            unique_dest_7d=1, amount_zscore=0.0, amount_vs_avg_ratio=1.0,
            is_amount_outlier=False, destination_risk_score=1, risk_score_delta=0,
            is_high_risk_dest=False, is_fatf_greylist=False, is_fatf_blacklist=False,
            is_cross_border=False, is_new_beneficiary=False, dest_account_age_days=365,
            customer_risk_rating=2, prior_alert_count=0, is_high_risk_customer=False,
            has_prior_alerts=False, channel_switch_flag=False, time_of_day_risk=0.1,
            is_round_amount=False, is_structuring_pattern=False,
        )
        defaults.update(kwargs)
        return FeatureVector(**defaults)

    def test_clean_transaction_scores_low(self):
        fv    = self._make_fv()
        score = _heuristic_score(fv)
        assert score < 0.30

    def test_fatf_blacklist_adds_high_score(self):
        fv_clean = self._make_fv()
        fv_black = self._make_fv(is_fatf_blacklist=True)
        assert _heuristic_score(fv_black) > _heuristic_score(fv_clean) + 0.15

    def test_fatf_greylist_adds_moderate_score(self):
        fv_clean = self._make_fv()
        fv_grey  = self._make_fv(is_fatf_greylist=True)
        assert _heuristic_score(fv_grey) > _heuristic_score(fv_clean)

    def test_structuring_pattern_adds_significant_score(self):
        fv_clean   = self._make_fv()
        fv_struct  = self._make_fv(is_structuring_pattern=True)
        assert _heuristic_score(fv_struct) > _heuristic_score(fv_clean) + 0.05

    def test_multiple_flags_cumulate(self):
        fv_single = self._make_fv(is_fatf_greylist=True)
        fv_multi  = self._make_fv(
            is_fatf_greylist=True,
            is_high_risk_dest=True,
            is_amount_outlier=True,
            is_new_beneficiary=True,
        )
        assert _heuristic_score(fv_multi) > _heuristic_score(fv_single)

    def test_score_never_exceeds_0_99(self):
        fv = self._make_fv(
            is_fatf_blacklist=True, is_fatf_greylist=True,
            is_high_risk_dest=True, is_amount_outlier=True,
            is_structuring_pattern=True, is_new_beneficiary=True,
            is_high_risk_customer=True, has_prior_alerts=True,
            amount_zscore=10.0, count_24h=20, customer_risk_rating=5,
        )
        assert _heuristic_score(fv) <= 0.99

    def test_score_never_negative(self):
        fv = self._make_fv()
        assert _heuristic_score(fv) >= 0.0

    def test_heuristic_shap_returns_5_features(self):
        fv    = self._make_fv(is_fatf_greylist=True, amount_zscore=3.0)
        score = _heuristic_score(fv)
        shap  = _heuristic_shap(fv, score)
        assert len(shap.top_features) == 5

    def test_heuristic_shap_features_sorted_by_abs_contribution(self):
        fv    = self._make_fv(is_fatf_greylist=True, is_high_risk_dest=True)
        score = _heuristic_score(fv)
        shap  = _heuristic_shap(fv, score)
        abs_vals = [f.abs_contribution for f in shap.top_features]
        assert abs_vals == sorted(abs_vals, reverse=True)

    def test_heuristic_shap_predicted_score_matches(self):
        fv    = self._make_fv()
        score = _heuristic_score(fv)
        shap  = _heuristic_shap(fv, score)
        assert shap.predicted_score == score


# ══════════════════════════════════════════════════════════════════════════
# 4. xgboost_scorer.py — full scorer
# ══════════════════════════════════════════════════════════════════════════

class TestXGBoostScorer:

    def test_returns_scorer_output(self):
        fv     = make_fv()
        result = score_transaction(fv)
        assert isinstance(result, ScorerOutput)

    def test_risk_score_in_range(self):
        fv     = make_fv()
        result = score_transaction(fv)
        assert 0.0 <= result.risk_score <= 1.0

    def test_risk_class_is_valid_enum(self):
        fv     = make_fv()
        result = score_transaction(fv)
        assert result.risk_class in (RiskClass.HIGH, RiskClass.MEDIUM, RiskClass.LOW)

    def test_transaction_id_preserved(self):
        fv     = make_fv(transaction_id="TXN-ID-CHECK")
        result = score_transaction(fv)
        assert result.transaction_id == "TXN-ID-CHECK"

    def test_latency_ms_is_positive(self):
        fv     = make_fv()
        result = score_transaction(fv)
        assert result.latency_ms > 0

    def test_scored_at_is_set(self):
        fv     = make_fv()
        result = score_transaction(fv)
        assert result.scored_at is not None

    def test_shap_explanation_present(self):
        fv     = make_fv()
        result = score_transaction(fv)
        assert result.shap_explanation is not None
        assert len(result.shap_explanation.top_features) > 0

    def test_model_version_set(self):
        fv     = make_fv()
        result = score_transaction(fv)
        assert result.model_version != ""

    def test_high_risk_transaction_scores_high(self):
        """A textbook high-risk transaction should score HIGH."""
        event = make_event(
            amount=200000.0,
            jurisdiction_destination="RU",
            product_type="WIRE_TRANSFER",
            timestamp=datetime(2026, 6, 13, 3, 0, 0, tzinfo=timezone.utc),
        )
        store = make_store(avg_amount=3000.0, risk_rating=4, prior_alerts=2)
        fv    = build_feature_vector(event, store)
        result = score_transaction(fv, product_type="WIRE_TRANSFER", jurisdiction_destination="RU")
        assert result.risk_class == RiskClass.HIGH
        assert result.risk_score > 0.7

    def test_low_risk_transaction_scores_low(self):
        """A clean domestic transaction should score LOW."""
        event = make_event(
            amount=1500.0,
            jurisdiction_origin="US",
            jurisdiction_destination="US",
            product_type="ACH",
        )
        store = make_store(avg_amount=2000.0, risk_rating=1, prior_alerts=0)
        fv    = build_feature_vector(event, store)
        result = score_transaction(fv, product_type="ACH", jurisdiction_destination="US")
        assert result.risk_class == RiskClass.LOW
        assert result.risk_score < 0.45

    def test_blacklisted_destination_always_high(self):
        """FATF blacklisted destination (IR/KP) must produce HIGH risk."""
        event = make_event(
            amount=50000.0,
            jurisdiction_destination="IR",
            product_type="SWIFT_TRANSFER",
        )
        store = make_store(avg_amount=5000.0)
        fv    = build_feature_vector(event, store)
        result = score_transaction(fv, product_type="SWIFT_TRANSFER", jurisdiction_destination="IR")
        assert result.risk_class == RiskClass.HIGH

    def test_product_jurisdiction_threshold_respected(self):
        """Wire to AE should use tighter thresholds than Wire to US."""
        event_ae = make_event(
            amount=30000.0,
            jurisdiction_destination="AE",
            product_type="WIRE_TRANSFER",
        )
        event_us = make_event(
            amount=30000.0,
            jurisdiction_destination="US",
            product_type="WIRE_TRANSFER",
        )
        store = make_store(avg_amount=5000.0)
        fv_ae = build_feature_vector(event_ae, store)
        fv_us = build_feature_vector(event_us, store)

        result_ae = score_transaction(fv_ae, "WIRE_TRANSFER", "AE")
        result_us = score_transaction(fv_us, "WIRE_TRANSFER", "US")

        # AE destination should produce higher or equal risk class
        risk_order = {RiskClass.LOW: 0, RiskClass.MEDIUM: 1, RiskClass.HIGH: 2}
        assert risk_order[result_ae.risk_class] >= risk_order[result_us.risk_class]

    def test_scorer_mode_is_xgboost_when_model_loaded(self):
        if _BOOSTER is None:
            pytest.skip("Model not found")
        fv     = make_fv()
        result = score_transaction(fv)
        assert result.scorer_mode == "xgboost"

    def test_feature_names_length_matches_to_model_input(self):
        fv = make_fv()
        assert len(FEATURE_NAMES) == len(fv.to_model_input())

    def test_consecutive_calls_are_deterministic(self):
        """Same input must always produce same output — model is stateless."""
        fv      = make_fv(amount=75000.0, jurisdiction_destination="AE")
        result1 = score_transaction(fv)
        result2 = score_transaction(fv)
        assert result1.risk_score == result2.risk_score
        assert result1.risk_class == result2.risk_class

    def test_amount_zscore_appears_in_shap_top5_for_outlier(self):
        """When amount is a huge outlier, zscore should appear in top SHAP features."""
        event = make_event(amount=500000.0)
        store = make_store(avg_amount=2000.0)
        fv    = build_feature_vector(event, store)
        result = score_transaction(fv)
        feature_names_in_top5 = [f.feature for f in result.shap_explanation.top_features]
        assert any("zscore" in n or "outlier" in n or "risk" in n for n in feature_names_in_top5)


# ══════════════════════════════════════════════════════════════════════════
# 5. Integration — feature pipeline → ML scorer end-to-end
# ══════════════════════════════════════════════════════════════════════════

class TestMLScorerIntegration:

    def test_full_pipeline_high_risk_transaction(self):
        event = TransactionEvent(
            transaction_id="TXN-INTEG-HIGH",
            customer_id="CUST-INTEG-01",
            amount=150000.0,
            currency="USD",
            channel="WIRE",
            origin_account="ACC-US-111",
            destination_account="ACC-RU-999",
            jurisdiction_origin="US",
            jurisdiction_destination="RU",
            product_type="WIRE_TRANSFER",
            timestamp=datetime(2026, 6, 13, 1, 30, 0, tzinfo=timezone.utc),
        )
        store = FeatureStoreClient()
        store.seed_customer("CUST-INTEG-01",
            avg_amount=4000.0, risk_rating=4,
            prior_alerts=2, account_age_days=90,
        )
        fv     = build_feature_vector(event, store)
        result = score_transaction(fv, "WIRE_TRANSFER", "RU")

        assert result.risk_class == RiskClass.HIGH
        assert result.risk_score > 0.5
        assert len(result.shap_explanation.top_features) == 5
        assert result.transaction_id == "TXN-INTEG-HIGH"
        assert result.scorer_mode in ("xgboost", "heuristic")

    def test_full_pipeline_low_risk_transaction(self):
        event = TransactionEvent(
            transaction_id="TXN-INTEG-LOW",
            customer_id="CUST-INTEG-02",
            amount=800.0,
            currency="USD",
            channel="ACH",
            origin_account="ACC-US-222",
            destination_account="ACC-US-333",
            jurisdiction_origin="US",
            jurisdiction_destination="US",
            product_type="ACH_PAYMENT",
            timestamp=datetime(2026, 6, 13, 11, 0, 0, tzinfo=timezone.utc),
        )
        store = FeatureStoreClient()
        store.seed_customer("CUST-INTEG-02",
            avg_amount=1000.0, risk_rating=1,
            prior_alerts=0, account_age_days=730,
        )
        # Seed some normal transaction history
        for i in range(5):
            store.append_customer_txn("CUST-INTEG-02", {
                "transaction_id": f"TXN-HIST-{i}",
                "amount": 950.0, "currency": "USD", "channel": "ACH",
                "destination_account": "ACC-US-333",
                "jurisdiction_destination": "US",
                "timestamp": "2026-06-10T10:00:00+00:00",
            })

        fv     = build_feature_vector(event, store)
        result = score_transaction(fv, "ACH_PAYMENT", "US")

        assert result.risk_class == RiskClass.LOW
        assert result.risk_score < 0.50

    def test_scorer_output_serialises_to_json(self):
        """ScorerOutput must be JSON-serialisable for API response."""
        fv     = make_fv()
        result = score_transaction(fv)
        json_str = result.model_dump_json()
        assert "risk_score" in json_str
        assert "risk_class" in json_str
        assert "top_features" in json_str

    def test_shap_feature_values_match_feature_vector(self):
        """SHAP feature values must match what was actually in the FeatureVector."""
        event = make_event(amount=50000.0, jurisdiction_destination="AE")
        store = make_store(avg_amount=5000.0)
        fv    = build_feature_vector(event, store)
        result = score_transaction(fv)

        fv_dict = fv.model_dump()
        for feature_contrib in result.shap_explanation.top_features:
            name = feature_contrib.feature
            if name in fv_dict:
                expected = round(float(fv_dict[name]), 4)
                assert feature_contrib.value == expected, (
                    f"SHAP value mismatch for feature '{name}': "
                    f"expected {expected}, got {feature_contrib.value}"
                )
